### ISSUE TITLE
Blocking when trying to deploy to Android?

### ISSUE THREAD

**Issue by Justinfront** [nmehost/acadnme#1]
'N' below represent the digits found on the Android Acadnme(v1.0) app top left corner.

haxelib run nme cppia --deploy=NNN.NNN.NNN.NNN

---

|             |
|__  _  __  **|
|  | \/  ||**|
|\  \  \ /||**|
|_|\_|\/|_||**|
|             |
|_____________|

NME Command-Line Tools(5.4.0 @ 'C:\haxelibrary/nme/git')
Use "nme help" for more commands
        1 file(s) copied.
Error: Could not connect to #function:1 : Blocking

Can you advise if there are additional settings on android device or any ways to trouble shoot, are there any aspects I have missed?

For reference....

haxelib list
acadnme: [1.0.3]
actuate: 1.7.5 1.8.2 [1.8.3]
air3: [0.0.1]
box2d: [1.2.3]
cocktail: [1.0.0-beta.5]
datetime: [3.0.0]
feffects: [3.1.0]
flow: git [dev:C:\HaxeToolkit\haxe\lib/flow/git]
format: [3.1.2]
gm2d: 3.2.5 [3.3.1]
haxelib_client: [3.2.0-rc.3]
HaxePunk: [2.5.3]
haxeui-file-dialogs: [0.1.1]
haxeui-rich-text: [0.1.2]
haxeui-webview: [0.1.1]
haxeui: 1.4.6 1.7.0 git [dev:C:\HaxeToolkit\haxe\lib/haxeui/git]
hscript: 2.0.1 [2.0.4]
hxcpp: 10-Wwx2014 3.2.102 3.2.37 3.2.81 3.2.81_ git [dev:C:\haxelibrary/hxcpp/git]
hxDaedalus: git [dev:C:\haxelibrary/hxDaedalus/git/src]
hxjava: [3.1.0]
hxsl: [2.0.5]
layout: [1.2.0]
lime-samples: [2.2.0]
lime-tools: [1.5.7]
lime: 1.0.1 2.0.0 2.1.1 2.1.3 [2.3.0] 2.3.3
luxe: git [dev:C:\HaxeToolkit\haxe\lib/luxe/git]
nme-dev: [1.3.5]
nme: git [dev:C:\haxelibrary/nme/git]
openfl-bitfive: [2.1.6]
openfl-html5-dom: [1.2.2]
openfl-html5: [1.4.2-beta]
openfl-samples: 1.3.0 2.1.0 [2.2.2]
openfl: 2.0.1 2.1.6 [2.2.6] 3.0.3
openflump: [1.0.0]
polygonal-ai - Copy: [1.0.0]
polygonal-ai: [1.0.0]
polygonal-ds - Copy: [1.4.1]
polygonal-ds: [1.4.1]
polygonal-printf - Copy: [1.0.2-beta]
polygonal-printf: [1.0.2-beta]
snow: git [dev:C:\HaxeToolkit\haxe\lib/snow/git]
svg: [1.0.8]
swf: 1.5.2 1.7.0 1.7.7 [1.8.2]
waxe-works: [1.0.4]
waxe: [3.1.1]
yagp: [1.1.4]

I also tried a cable with --deploy=abt

running to cppia locally works fine though.

**Comment by hughsando** [comment]
Try with zero or one minus signs before "deploy" on command line.

Also, are you one the same network? So that you host ip address starts with
the same numbers as your android device ?

**Comment by Justinfront** [comment]
if I do ipconfig from cmd I get the same first two digits for IPv4, but the second two are different. The pc is connected via network cable the samsung is connected via wifi, but I downloaded acadnme from google play store so I know the device is connected.  0 does not work -1 seem the same.

**Comment by Justinfront** [comment]
the piratepig works from the options list, do I need to some how check which ports are closed and can I choose which one to send it via?

**Comment by hughsando** [comment]
I suspect it might be a firewwall issue.  Are you on a home (consumer)
router or a work one?
Sometimes non-http port can be blocked.  acadnme uses port 0xacad = 44205.
Also, killing the app and starting again can sometimes print a different ip
address and this can be worth a go.

**Comment by Justinfront** [comment]
it's work.  I tried restarting gave same ip

**Comment by Justinfront** [comment]
Ok I managed to find a htc mobile and it worked fine so not sure why the samsung tablet blocked it.

**Comment by Justinfront** [comment]
it would be useful to know what sort of settings on devices might cause such blocks but it's not really a code issue so closing.
